
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module zad2(

	//////////// Audio //////////
	input 		          		AUD_ADCDAT,
	inout 		          		AUD_ADCLRCK,
	inout 		          		AUD_BCLK,
	output		          		AUD_DACDAT,
	inout 		          		AUD_DACLRCK,
	output		          		AUD_XCK,

	//////////// CLOCK //////////
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	input 		          		CLOCK4_50,
	input 		          		CLOCK_50,

	//////////// I2C for Audio and Video-In //////////
	output		          		FPGA_I2C_SCLK,
	inout 		          		FPGA_I2C_SDAT,

	//////////// KEY //////////
	input 		     [3:0]		KEY
);



//=======================================================
//  REG/WIRE declarations
//=======================================================




//=======================================================
//  Structural coding
//=======================================================

audio au(.clk_clk    (CLOCK_50),       //       clk.clk
		.reset_reset_n (KEY[0]), //     reset.reset_n
		.av_i2c_SDAT   (FPGA_I2C_SDAT),   //    av_i2c.SDAT
		.av_i2c_SCLK   (FPGA_I2C_SCLK),   //          .SCLK
		.audio_ADCDAT  (AUD_ADCDAT),  //     audio.ADCDAT
		.audio_ADCLRCK (AUD_ADCLRCK), //          .ADCLRCK
		.audio_BCLK    (AUD_BCLK),    //          .BCLK
		.audio_DACDAT  (AUD_DACDAT),  //          .DACDAT
		.audio_DACLRCK (AUD_DACLRCK), //          .DACLRCK
		.audio_clk_clk (AUD_XCK) ); // audio_clk.clk;


endmodule
