
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module zad4(

	//////////// CLOCK //////////
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	input 		          		CLOCK4_50,
	input 		          		CLOCK_50,

	//////////// LED //////////
	output		     [9:0]		LEDR
);



//=======================================================
//  REG/WIRE declarations
//=======================================================

wire _10Hz, _10Hz_CLOCK_edge;
wire _new_clock;
wire [39:0]dist;
wire [9:0]comps[10];


//=======================================================
//  Structural coding
//=======================================================

_10Hz_CLOCK clk0(_10Hz,CLOCK_50);

_edge_detector det0(_10Hz_CLOCK_edg,CLOCK_50,_10Hz);

_UP_and_DOWN slid0(dist,_10Hz_CLOCK_edg);

generate
	genvar i;
	for (i = 0 ; i < 10 ; i = i + 1) begin: cmp_loop
		_Cnt_to_Cmp cmp(comps[i],dist[(i*4)+:4]);
	end
endgenerate

_PWM_SAW #(10,10)(LEDR,1023,{	comps[0],comps[1],comps[2],comps[3],comps[4],
										comps[5],comps[6],comps[7],comps[8],comps[9]},CLOCK_50);

endmodule
